name: Latest semver tag

on:
  workflow_call:
    inputs:
      repo:
        type: string
        description: Repository
        required: true
    outputs:
      ref:
        description: The tag of the latest release
        value: ${{ jobs.run.outputs.ref }}
      ver:
        description: "The semver of the latest release (without a leading 'v')"
        value: ${{ jobs.run.outputs.ver }}
jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.find.outputs.ref }}
      ver: ${{ steps.find.outputs.ver }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: lf-lang/${{ inputs.repo }}
      - name: Install semver-tool
        run: |
          wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver
          semver --version
      - name: Fetch all tags
        run: git fetch --all --tags
      - name: Find the latest release
        id: find
        run: |
          export tag=$(./latest-release.sh)
          echo "::set-output name=ref::${tag}"
          shopt -s extglob
          export ver="${tag##v}"
          echo "::set-output name=ver::${ver}"
          echo "Latest release tag: ${tag}"
          echo "Without a leading 'v': ${ver}"
