name: Greatest SemVer Tag
description: Return the greatest semantic version tag
inputs:
  path:
    type: string
    description: Path to the repository
    default: ${{ github.workspace }}
outputs:
  tag:
    description: Greatest semver tag
    value: ${{ steps.find.outputs.tag }}
  no-prefix:
    description: "Greatest semver tag sans 'v'"
    value: ${{ steps.strip.outputs.ver }}
branding:
  icon: tag
  color: green
runs:
  using: composite
  steps:
    - name: Install semver-tool
      run: |
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
      shell: bash
    - name: Install greatest-semver-tag
      run: |
        wget -O /usr/local/bin/greatest-semver-tag https://github.com/lhstrh/greatest-semver-tag/blob/no-checkout/greatest-semver-tag.sh
        chmod +x /usr/local/bin/greatest-semver-tag
      shell: bash
    - name: Fetch all tags
      run: git fetch --all --tags
      working-directory: ${{ inputs.path }}
      shell: bash
    - name: Find the greatest semver tag
      id: find
      working-directory: ${{ inputs.path }}
      run: |
        echo "::set-output name=tag::$(greatest-semver-tag)"
      shell: bash
    - name: Strip off 'v' prefix if there is one
      id: strip
      run: |
        tag="${{ steps.find.outputs.tag }}" && shopt -s extglob && echo "::set-output name=ver::${tag##v}"
      shell: bash
    - name: Print results
      run: |
        echo "Latest release tag: ${{ steps.find.outputs.tag }}"
        echo "Without a leading 'v': ${{ steps.strip.outputs.ver }}"
      shell: bash
