name: Latest semver tag

inputs:
  repo:
    type: string
    description: Repository name
    required: true
outputs:
  tag:
    description: Latest semver tag
    value: ${{ steps.find.outputs.tag }}
  no-prefix:
    description: "Latest semver tag sans 'v'"
    value: ${{ steps.strip.outputs.ver }}

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo }}
    - name: Install semver-tool
      run: |
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
        semver --version
      shell: bash
    - name: Fetch latest-release script
      run: |
        wget https://raw.githubusercontent.com/lf-lang/lingua-franca/master/.github/scripts/latest-release.sh
        chmod +x latest-release.sh
        shell: bash
    - name: Fetch all tags
      run: git fetch --all --tags
      shell: bash
    - name: Find the latest release
      id: find
      run: |
        echo "::set-output name=tag::$(./latest-release.sh)"
      shell: bash
    - name: Strip off 'v' prefix if there is one
      id: strip
      run: |
        tag="${{ steps.find.outputs.tag }}" && shopt -s extglob && echo "::set-output name=ver::${tag##v}"
      shell: bash
    - name: Print results
      run: |
        echo "Latest release tag: ${{ steps.find.outputs.tag }}"
        echo "Without a leading 'v': ${{ steps.strip.outputs.ver }}"
      shell: bash