name: SemVer Tag
description: Find the greatest semantic version tag and return it, along with a patch, minor, and major increment.
inputs:
  path:
    type: string
    description: Path to the repository
    default: ${{ github.workspace }}
  prefix:
    type: string
    description: Prefix used in version tags
    default: 'v'

outputs:
  current:
    description: Current semver tag
    value: ${{ steps.find.outputs.tag }}
  next-patch:
    description: Patch increment (over current semver tag)
    value: ${{ steps.incr.outputs.patch }}
  next-minor:
    description: Minor increment (over current semver tag)
    value: ${{ steps.incr.outputs.minor }}
  next-major:
    description: Major increment (over current semver tag)
    value: ${{ steps.incr.outputs.major }}
  next-release:
    description: Release increment (over current semver tag)
    value: ${{ steps.incr.outputs.release }}
  next-prerelease:
    description: Prerelease increment (over current semver tag)
    value: ${{ steps.incr.outputs.prerelease }}  

branding:
  icon: tag
  color: green
runs:
  using: composite
  steps:
    - name: Install semver-tool
      run: |
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
      shell: bash
    - name: Install greatest-semver-tag
      run: |
        wget -O /usr/local/bin/greatest-semver-tag https://raw.githubusercontent.com/lhstrh/greatest-semver-tag/main/greatest-semver-tag.sh
        chmod +x /usr/local/bin/greatest-semver-tag
      shell: bash
    - name: Fetch all tags
      run: git fetch --all --tags
      working-directory: ${{ inputs.path }}
      shell: bash
    - name: Find the greatest semver tag
      id: find
      working-directory: ${{ inputs.path }}
      run: |
        echo "::set-output name=tag::$(greatest-semver-tag)"
      shell: bash
    - name: Produce increments
      id: incr
      run: |
        echo "::set-output name=patch::$(semver bump patch ${{ steps.find.outputs.tag }})"
        echo "::set-output name=minor::$(semver bump minor ${{ steps.find.outputs.tag }})"
        echo "::set-output name=major::$(semver bump major ${{ steps.find.outputs.tag }})"
        echo "::set-output name=release::$(semver bump release ${{ steps.find.outputs.tag }})"
        echo "::set-output name=prerelease::$(semver bump prerel ${{ steps.find.outputs.tag }})"
      shell: bash  
    - name: Print results
      run: |
        echo "Current tag: ${{ steps.find.outputs.tag }}"
        echo "Patch increment: ${{ steps.incr.outputs.patch }}"
        echo "Minor increment: ${{ steps.incr.outputs.minor }}"
        echo "Major increment: ${{ steps.incr.outputs.major }}"
        echo "Release increment: ${{ steps.incr.outputs.release }}"
        echo "Prerelease increment: ${{ steps.incr.outputs.prerelease }}"
      shell: bash
