name: Latest semver tag

inputs:
  repo:
    type: string
    description: Repository name
    required: true
outputs:
  tag:
    description: Latest semver tag
    value: ${{ steps.find.outputs.tag }}
  no-prefix:
    description: "Latest semver tag sans 'v'"
    value: ${{ steps.find.outputs.ver }}

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repo }}
    - name: Install semver-tool
      run: |
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
        semver --version
      shell: bash
    - name: Fetch all tags
      run: git fetch --all --tags
      shell: bash
    - name: Find the latest release
      id: find
      run: >
        tag=$(./latest-release.sh)
        echo "::set-output name=tag::${tag}"
        shopt -s extglob
        ver="${tag##v}"
        echo "::set-output name=ver::${ver}"
        echo "Latest release tag: ${tag}"
        echo "Without a leading 'v': ${ver}"
      shell: bash
