name: SemVer Tag
description: Find the greatest semantic version tag and return it, along with a patch, minor, and major increment.
inputs:
  path:
    type: string
    description: Path to the repository
    default: ${{ github.workspace }}
  prefix:
    type: string
    description: Prefix used in version tags
    default: 'v'

outputs:
  current:
    description: Current semver tag
    value: ${{ steps.find.outputs.tag }}
  current-bare:
    description: "Current semver tag stripped from leading 'v'"
    value: ${{ steps.strip.outputs.ver }}
  next-patch:
    description: Patch increment (over current semver tag)
    value: ${{ steps.incr.outputs.patch }}
  next-patch-bare:
    description: "Patch increment stripped from leading 'v'"
    value: ${{ steps.strip.outputs.patch }}
  next-minor:
    description: Minor increment (over current semver tag)
    value: ${{ steps.incr.outputs.minor }}
  next-minor-bare:
    description: "Minor increment stripped from leading 'v'"
    value: ${{ steps.strip.outputs.minor }}
  next-major:
    description: Major increment (over current semver tag)
    value: ${{ steps.incr.outputs.major }}
  next-major-bare:
    description: "Major increment stripped from leading 'v'"
    value: ${{ steps.strip.outputs.major }}

branding:
  icon: tag
  color: green
runs:
  using: composite
  steps:
    - name: Install semver-tool
      run: |
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
      shell: bash
    - name: Install greatest-semver-tag
      run: |
        wget -O /usr/local/bin/greatest-semver-tag https://raw.githubusercontent.com/lhstrh/greatest-semver-tag/main/greatest-semver-tag.sh
        chmod +x /usr/local/bin/greatest-semver-tag
      shell: bash
    - name: Fetch all tags
      run: git fetch --all --tags
      working-directory: ${{ inputs.path }}
      shell: bash
    - name: Find the greatest semver tag
      id: find
      working-directory: ${{ inputs.path }}
      run: |
        echo "::set-output name=tag::$(greatest-semver-tag)"
      shell: bash
    - name: Produce increments
      id: incr
      run: |
        echo "::set-output name=patch::$(semver bump patch ${{ steps.find.outputs.tag }})"
        echo "::set-output name=minor::$(semver bump minor ${{ steps.find.outputs.tag }})"
        echo "::set-output name=major::$(semver bump major ${{ steps.find.outputs.tag }})"
      shell: bash  
    - name: Produce bare versions (without leading 'v')
      id: strip
      run: |
        tag="${{ steps.find.outputs.tag }}" && shopt -s extglob && echo "::set-output name=ver::${tag##v}"
        tag="${{ steps.incr.outputs.patch }}" && shopt -s extglob && echo "::set-output name=patch::${tag##v}"
        tag="${{ steps.incr.outputs.minor }}" && shopt -s extglob && echo "::set-output name=minor::${tag##v}"
        tag="${{ steps.incr.outputs.major }}" && shopt -s extglob && echo "::set-output name=major::${tag##v}"
      shell: bash
    - name: Print results
      run: |
        echo "Current tag: ${{ steps.find.outputs.tag }}"
        echo "Patch increment: ${{ steps.incr.outputs.patch }}"
        echo "Minor increment: ${{ steps.incr.outputs.minor }}"
        echo "Major increment: ${{ steps.incr.outputs.major }}"
      shell: bash
