name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run local action with planned=0.0.0
        uses: ./
        with:
          planned: 0.0.0
        id: semver-tag
      - name: Run local action with bump=major, planned=1000000000.0.0
        uses: ./
        with:
          bump: major
          planned: 1000000000.0.0
        id: billionth
      - name: Run local action with override=1.2.3
        uses: ./
        with:
          bump: minor
          override: 1.2.3
        id: override
      - name: Run local action with build=foo
        uses: ./
        with:
          build: foo
        id: foo-build
      - name: Run local action with repo=lhstrh/action-repo-semver
        uses: ./
        with:
          repo: lhstrh/action-repo-semver
          path: foo
      - name: Install semver-tool
        run: |
          wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver
          semver --version
      - name: Ensure outputs are not empty
        run: |
          [[ ! -z "${{ steps.semver-tag.outputs.current }}" ]] || exit 1
          [[ ! -z "${{ steps.semver-tag.outputs.next-patch }}" ]] || exit 1
          [[ ! -z "${{ steps.semver-tag.outputs.next-minor }}" ]] || exit 1
          [[ ! -z "${{ steps.semver-tag.outputs.next-major }}" ]] || exit 1
          [[ ! -z "${{ steps.semver-tag.outputs.next-prerelease }}" ]] || exit 1
          [[ ! -z "${{ steps.semver-tag.outputs.next-release }}" ]] || exit 1
      - name: Check relationships between versions
        run: |
          [[ $(semver compare ${{ steps.semver-tag.outputs.current }} 0.0.0) -eq 1 ]] || exit 1
          [[ $(semver compare ${{ steps.semver-tag.outputs.next-patch }} ${{ steps.semver-tag.outputs.current }}) -eq 1 ]] || exit 1
          [[ $(semver compare ${{ steps.semver-tag.outputs.next-minor }} ${{ steps.semver-tag.outputs.next-patch }}) -eq 1 ]] || exit 1
          [[ $(semver compare ${{ steps.semver-tag.outputs.next-major }} ${{ steps.semver-tag.outputs.next-minor }}) -eq 1 ]] || exit 1
          [[ $(semver compare ${{ steps.semver-tag.outputs.next-release }} ${{ steps.semver-tag.outputs.next-prerelease }}) -eq 1 ]] || exit 1
      - name: Ensure 0.0.0 is not greater than whatever the current version is
        run: |
          [[ "${{ steps.semver-tag.outputs.planned-is-valid }}" = "false" ]] || exit 1
      - name: Ensure 1000000000.0.0 is greater than whatever the current version is
        run: |
          [[ "${{ steps.billionth.outputs.planned-is-valid }}" = "true" ]] || exit 1
      - name: Check major bump on billionth
        run: |
          [[ "${{ steps.billionth.outputs.bump }}" = "${{ steps.billionth.outputs.next-major }}" ]] || exit 1
      - name: Check minor bump on override
        run: |
          [[ "${{ steps.override.outputs.bump }}" = "1.3.0" ]] || exit 1
      - name: Ensure next-build of foo-build is foo
        run: |
          [[ "$(semver get build ${{ steps.foo-build.outputs.next-build }})" = "foo" ]] || exit 1
