name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: semver-tag
      - name: Install semver-tool
        run: |
          wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver
          semver --version
      - name: Ensure outputs are not empty
        run: |
          [[ ! -z "${{ steps.semver-tag.outputs.current }}" ]] || exit 1
          [[ ! -z "${{ steps.semver-tag.outputs.next-patch }}" ]] || exit 1
          [[ ! -z "${{ steps.semver-tag.outputs.next-minor }}" ]] || exit 1
          [[ ! -z "${{ steps.semver-tag.outputs.next-major }}" ]] || exit 1
          [[ ! -z "${{ steps.semver-tag.outputs.next-release }}" ]] || exit 1
          [[ ! -z "${{ steps.semver-tag.outputs.next-prerelease }}" ]] || exit 1
      - name: Ensure outputs are semver and greater than 0.0.0
        run: |
          [[ $(semver compare ${{ steps.semver-tag.outputs.current }} 0.0.0) -eq 1 ]] || exit 1
          [[ $(semver compare ${{ steps.semver-tag.outputs.current-bare }} 0.0.0) -eq 1 ]] || exit 1
          [[ $(semver compare ${{ steps.semver-tag.outputs.next-patch }} ${{ steps.semver-tag.outputs.current }}) -eq 1 ]] || exit 1
          [[ $(semver compare ${{ steps.semver-tag.outputs.next-minor }} ${{ steps.semver-tag.outputs.next-patch }}) -eq 1 ]] || exit 1
          [[ $(semver compare ${{ steps.semver-tag.outputs.next-major }} ${{ steps.semver-tag.outputs.next-minor }}) -eq 1 ]] || exit 1