name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: run-composite
        with:
          repo: lf-lang/lingua-franca
          - name: Install semver-tool
      run: |
        wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x /usr/local/bin/semver
        semver --version
      - name: Perform tests
        run: |
          semver compare ${{ steps.run-composite.outputs.tag }} 0.0.0
          semver compare ${{ steps.run-composite.outputs.no-prefix }} 0.0.0
