name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: run-composite
        with:
          repo: lf-lang/lingua-franca
      - name: Install semver-tool
        run: |
          wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver
          semver --version
      - name: Ensure outputs are not empty
        run: |
          [[ ! -z "${{ steps.run-composite.outputs.tag }}" ]] || exit 1
          [[ ! -z "${{ steps.run-composite.outputs.no-prefix }}" ]] || exit 1
      - name: Ensure outputs are semver and greater than 0.0.0
        run: |
          [[ $(semver compare ${{ steps.run-composite.outputs.tag }} 0.0.0) -eq 1 ]] || exit 1
          [[ $(semver compare ${{ steps.run-composite.outputs.no-prefix }} 0.0.0) -eq 1 ]] || exit 1
